// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ImagePath {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ImageInfo {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub path: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub filename: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub format: ::prost::alloc::string::String,
    #[prost(uint32, tag = "5")]
    pub width: u32,
    #[prost(uint32, tag = "6")]
    pub height: u32,
    #[prost(uint64, tag = "7")]
    pub file_size_bytes: u64,
    #[prost(string, tag = "8")]
    pub pixel_format: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub color_space: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "10")]
    pub metadata: ::core::option::Option<MetadataInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MetadataInfo {
    #[prost(string, optional, tag = "1")]
    pub make: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "2")]
    pub model: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "3")]
    pub lens_model: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "4")]
    pub date_time_original: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "5")]
    pub exposure_time: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "6")]
    pub f_number: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, optional, tag = "7")]
    pub iso: ::core::option::Option<u32>,
    #[prost(string, optional, tag = "8")]
    pub focal_length: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(double, optional, tag = "9")]
    pub latitude: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "10")]
    pub longitude: ::core::option::Option<f64>,
    #[prost(double, optional, tag = "11")]
    pub altitude: ::core::option::Option<f64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DecodeRequest {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "2")]
    pub pixel_format: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, optional, tag = "3")]
    pub max_width: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "4")]
    pub max_height: ::core::option::Option<u32>,
    #[prost(bool, tag = "5")]
    pub read_metadata: bool,
    #[prost(bool, tag = "6")]
    pub apply_transfer: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PixelDataChunk {
    #[prost(uint32, tag = "1")]
    pub offset: u32,
    #[prost(bytes = "vec", tag = "2")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag = "3")]
    pub total_size: u32,
    #[prost(bool, tag = "4")]
    pub is_last: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EncodeRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub pixel_data: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag = "2")]
    pub width: u32,
    #[prost(uint32, tag = "3")]
    pub height: u32,
    #[prost(string, tag = "4")]
    pub layout: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub pixel_format: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub output_path: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub format: ::prost::alloc::string::String,
    #[prost(float, optional, tag = "8")]
    pub quality: ::core::option::Option<f32>,
    #[prost(bool, tag = "9")]
    pub lossless: bool,
    #[prost(uint32, tag = "10")]
    pub bit_depth: u32,
    #[prost(string, optional, tag = "11")]
    pub chroma_subsampling: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "12")]
    pub encoder: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, optional, tag = "13")]
    pub effort: ::core::option::Option<u32>,
    #[prost(message, optional, tag = "14")]
    pub metadata: ::core::option::Option<MetadataInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EncodeProgress {
    #[prost(float, tag = "1")]
    pub fraction: f32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(uint64, tag = "3")]
    pub bytes_written: u64,
    #[prost(bool, tag = "4")]
    pub done: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ThumbnailRequest {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub max_size: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ImageData {
    #[prost(bytes = "vec", tag = "1")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag = "2")]
    pub width: u32,
    #[prost(uint32, tag = "3")]
    pub height: u32,
    #[prost(string, tag = "4")]
    pub format: ::prost::alloc::string::String,
}
/// Generated client implementations.
pub mod image_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct ImageServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl ImageServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> ImageServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> ImageServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            ImageServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn load(
            &mut self,
            request: impl tonic::IntoRequest<super::ImagePath>,
        ) -> std::result::Result<tonic::Response<super::ImageInfo>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/photopipeline.image.ImageService/Load",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("photopipeline.image.ImageService", "Load"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn decode(
            &mut self,
            request: impl tonic::IntoRequest<super::DecodeRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::PixelDataChunk>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/photopipeline.image.ImageService/Decode",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("photopipeline.image.ImageService", "Decode"));
            self.inner.server_streaming(req, path, codec).await
        }
        pub async fn encode(
            &mut self,
            request: impl tonic::IntoRequest<super::EncodeRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::EncodeProgress>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/photopipeline.image.ImageService/Encode",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("photopipeline.image.ImageService", "Encode"));
            self.inner.server_streaming(req, path, codec).await
        }
        pub async fn get_thumbnail(
            &mut self,
            request: impl tonic::IntoRequest<super::ThumbnailRequest>,
        ) -> std::result::Result<tonic::Response<super::ImageData>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/photopipeline.image.ImageService/GetThumbnail",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("photopipeline.image.ImageService", "GetThumbnail"),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
